name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_WEB1: ashwinsajii/web1
  IMAGE_WEB2: ashwinsajii/web2

jobs:

  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build web1 image
        uses: docker/build-push-action@v5
        with:
          context: ./web1
          push: true
          tags: |
            ${{ env.IMAGE_WEB1 }}:latest
            ${{ env.IMAGE_WEB1 }}:${{ github.sha }}

      - name: Build web2 image
        uses: docker/build-push-action@v5
        with:
          context: ./web2
          push: true
          tags: |
            ${{ env.IMAGE_WEB2 }}:latest
            ${{ env.IMAGE_WEB2 }}:${{ github.sha }}

      - name: No tests yet
        run: echo "Skipping tests for now."
